### ISSUE TITLE
Update to Java 8

### ISSUE THREAD

**Issue by stsundermann** [UniTime/cpsolver#10]
Java 8 is widely adapted now and should be the default on most machines. Java 8 brings useful features like lambda expressions allowing more precise and shorter code in some situations.

Is there any reason to stay at a language level of 1.6?

**Comment by tomas-muller** [comment]
Yes, there are a few:

1) There are still a lot of production environments running UniTime that are NOT using Java 8. And while Java 8 offers some language improvements, they break backward compatibility.

2) It is a lot of work and testing. And the language improvements are mostly cosmetic, they would not make run the solver any faster.
