### ISSUE TITLE
Online class restriction 

### ISSUE THREAD

**Issue by KarthikRv93** [UniTime/cpsolver#15]
@tomas-muller, 
I had some query regarding the solver report.
In the Instructor solver, I see that there is a perturbation percentage report.
What does the perturbation percentage indicate? How does it affect the solver result?

Continuation of this question : 
https://github.com/UniTime/unitime/issues/48#issuecomment-476748856
I have added a hard constraint of the online classes, but the perturbation percentage went up from 0.34% to 70%.

**Comment by tomas-muller** [comment]
When the solver is in the MPP (Minimal Perturbation Problem) mode, it is desired to minimize the number of changes in the solution. In the case of the instructor assignment problem, this is done using the OriginalInstructor criterion.

The "Perturbation variables" parameter counts the number of variables (teaching assignments) that either do not have an initial assignment (instructor) or the initial assignment is different from the current assignment.

You can influence how much the solver tries to stick with the inital assignments by changing the weight of the OriginalInstructor criterion (Weight.OriginalInstructor parameter, defaults to 100).

**Comment by KarthikRv93** [comment]
@Thanks for your reply:)
