### ISSUE TITLE
Understanding of solver score calculation

### ISSUE THREAD

**Issue by KarthikRv93** [UniTime/cpsolver#16]
@tomas-muller, we are finding difficulty in understanding the logic behind the calculation of the scores involved while assigning a subject to an instructor based on various parameters set in the applications.

**_Screenshot 1: Solver score of Prof.Eric Kostelish_**
<img width="2548" alt="Screen Shot 2019-04-03 at 5 05 43 PM" src="https://user-images.githubusercontent.com/17763970/55520807-c2ea4f80-5632-11e9-8ffe-fb8c81c7aa78.png">

**_Screenshot2: Solver score of Prof.Tim Ferguson_**
<img width="2544" alt="Screen Shot 2019-04-03 at 5 03 36 PM" src="https://user-images.githubusercontent.com/17763970/55520755-8c143980-5632-11e9-9f22-1d29bc4725e4.png">

With reference to the screenshots above, Prof."Eric Kostelich" has been assigned with this course when he has not set any kind of preferences( Time preference = Neutral, No course preference). Where as prof."Tim Ferguson" has set the MAT-342 as his preferred course and the time preference matches with the time of the class. Yet he's not assigned with this class.
Under the objectives column  we are not able to interpret  how the values are calculated for entries such as Attribute preferences, same course, teaching preferences and time preferences. Specifically, we want to understand how Prof.Eric Kostelich's attribute preference is -2 and Prof.Tim Ferguson has +2. 

Please find the preferences info for both the professors : 

_**Prof.Eric Kostelishs attribute preferences**_ 
<img width="1204" alt="Screen Shot 2019-04-03 at 5 13 30 PM" src="https://user-images.githubusercontent.com/17763970/55521031-d649ea80-5633-11e9-86b5-bd826263f886.png">

**_Prof.Tim Ferguson's attribute preferences_** 
<img width="1203" alt="Screen Shot 2019-04-03 at 5 13 07 PM" src="https://user-images.githubusercontent.com/17763970/55521038-db0e9e80-5633-11e9-9168-b46e7e5af8f7.png">

**Comment by tomas-muller** [comment]
The Objectives column shows the difference in the parameter when the change is done. As the solver tries to minimize the weighted sum of various criteria, the preferences has the following values:
- Strongly Preferred -4
- Prefered -1
- Neutral 0
- Discouraged +1
- Strongly Discouraged +4

Please note that Available Instructors table considers the whole change, including the conflicting assignment that would have to be unassigned. So, because there would be one less teaching assignment assigned that prefers two attributes, the difference in the attribute preference would be +2 from what it is now.

In the Assigned Instructors table, the Objectives shows the change of just this particular assignment and as the instructor satisfies both prefered attributes, this assignment contributes to the overall attribute preference by -2 (please note that we want to minimize the overall value, so a negative value is what we want).

**Comment by KarthikRv93** [comment]
@tomas-muller,
Thanks for your reply :)
I understand the other part of your answer, but I don't understand when you say:

_" Please note that Available Instructors table considers the whole change, including the conflicting assignment that would have to be unassigned. So, because there would be one less teaching assignment assigned that prefers two attributes, the difference in the attribute preference would be +2 from what it is now
"_
In the above scenario :
MAT-342 has to be assigned to Prof.Tim Ferguson even though I consider all the constraints as you have mentioned in the above answer. 
I am asking this question because this is happening for a lot of other professors as well. So I want to understand is the factor that is causing wrong results so that we can change the data accordingly.

**Comment by tomas-muller** [comment]
Well, the question was about attribute preferences. The Prof."Eric Kostelich" is currently assigned to the section on the first screenshot and he is meeting both preferred attribute, hence the value -2 (-1 for each satisfied preferred attribute). This takes into account this one assignment and its contribution to the various optimization criteria.

The Prof.Tim Ferguson has currently a full schedule (I am guessing here), so assigning him to the above section would mean he would get removed from MAT 142 which looks like also has two satisfied preferred attributes. So, making the change (assigning Prof.Tim Ferguson to MAT 343 and leaving MAT 142 not assigned) has a difference in the attribute preferences +2 (no change for MAT 343 as we are swapping two instructors that meet both preferences, two no longer satisfied preferences for MAT 343).

Please note that you can explore a bigger change by following up on the assignments (click on the instructor in the Available Instructors table, than click on the unassigned teaching assignment and find a new instructor for it, etc.). For instance, see what a difference it would make in the cost to actually swap the two professors between the two courses. You can also see the Suggestions that try to do just that automatically (ordered by the cost of the change). Usually, if you left the solver running long enough, you should not be able to make any simple swap of two variables that would improve the overall solution value (while the solver cannot guarantee optimality, the produced solution is usually at least locally optimal).

You say that the results are wrong and that the MAT 342 (the screenshot is for MAT 343) **has to be** assigned to Prof.Tim Ferguson, I do not see that in the data. There is only that one soft course preference on the instructor that can be easily overpowered by other criteria (e.g., the two distribution preferences).

So, please, do try to make the changes you think the solver should have done and see if they are even feasible to make and what they would mean in terms of the overall solution value. It is possible you may need to adjust the weights of some of the criteria to better suit your needs (e.g., put more weight on the Course Preferences).
