### ISSUE TITLE
Round Robin prevents from terminating if no neighbour is selected

### ISSUE THREAD

**Issue by H3ADLESS** [UniTime/cpsolver#18]
Hey there,

I have just spend some time to detect why my custom solver didn't terminate. It's probably a good idea to return null, if all registered neighbourSelections fail to find a neighbour or check for terminationCondition. Adding a random selection helps preventing this issue.

Maybe there are other ways to avoid this problem? Probably the most selections will at some point return a valid neighbour.

This is the relating code of RoundRobinNeighbourSelection

```
public Neighbour<V, T> selectNeighbour(Solution<V, T> solution) {
        while (true) {
            int selectionIndex = getSelectionIndex();
            NeighbourSelection<V, T> selection = iSelections.get(selectionIndex % iSelections.size());
            Neighbour<V, T> neighbour = selection.selectNeighbour(solution);
            if (neighbour != null)
                return neighbour;
            changeSelection(selectionIndex);
        }
    }
```

**Comment by tomas-muller** [comment]
For a [NeighbourSelection](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/ifs/heuristics/NeighbourSelection.java), returning null is an indication that the neighborhood has been exhausted and the search should progress with the next one. For example, the [BranchBoundSelection](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/studentsct/heuristics/selection/BranchBoundSelection.java) (that is used by the student sectioning solver, and that tries to find the best possible schedule for each student while everything else is fixed) returns null when all student has been tried. Please note that the [NeighbourSelection.init(Solver)](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/ifs/heuristics/NeighbourSelection.java#L42) is called before the selection is used. It is, for instance, used to reset the list of students that will be tried during the next phase (consecutive calling of [NeighbourSelection. selectNeighbour(solution)](https://github.com/UniTime/cpsolver/blob/master/src/org/cpsolver/ifs/heuristics/NeighbourSelection.java#L51), until null is returned).

It is not, however, expected that all neighbor selections would keep returning null values and nothing else. That said, it would be possible to add a termination condition check within or just before the changeSelection called.
