### ISSUE TITLE
Less constrained timelocations

### ISSUE THREAD

**Issue by stsundermann** [UniTime/cpsolver#7]
I'd like to deploy a cpsolver based timetabling at my university. However, timetables are not as constrained as required by cpsolver at my university. In cpsolver if a lecture meets several times a week on different days, the start time is always the same. That's not the case at my university, e.g. a lecture might meet Mondays at 10:00 - 12:00 and Thursdays at 16:00 - 18:00. Is there a way to have this kind of timelocations with cpsolver?

**Comment by tomas-muller** [comment]
In short no. Each placement can take only a single time location (one combination of start time, length, days of the week, and date pattern). Allowing for more would make the domains way too big and impractical for the solver to work with.

It is possible, however, to model cases where a class needs multiple meetings that do not start at the same time, are of a different length or are placed in different rooms. In these cases, such a lecture needs to be split into multiple (single placement) lectures. These lectures can be tight together with distribution (group) constraints, e.g., requiring all such lectures to have the same room or to be placed on different days of the week.

This can be modeled easily in UniTime by nesting two Lecture subparts with the same number of classes one under the other.
